[package]
name = "aura"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
notify-rust = "4.11.3"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = 'abort'

